### PR TITLE
docs(IA-4870): updates to initial repo set up

### PR DESCRIPTION
**Pull request by cpate4**
- Made changes to update documentation (clean up readability), and
- Fixed build failure re: import order

### CODE REVIEW

**Comment by cpate4** [comment]
... just an FYI for this PR, we are waiting on a [terraform PR](https://github.com/broadinstitute/terraform-ap-deployments/pull/1461) to be applied to get secrets and auths setup

**Comment by mflinn-broad** [comment]
Terraform PR has been applied, if you re-run the GHAs they should work now

**Comment by cpate4** [comment]
@mflinn-broad - is there another thing that needs to be applied for [source-clear](https://github.com/DataBiosphere/terra-app-manager/actions/runs/8450534701/job/23154101721)?

**Comment by cpate4** [comment]
... and for those following along here, there is a [conversation going on in slack w/ INFOSEC](https://broadinstitute.slack.com/archives/CADU7L0SZ/p1711548197748029)

**Comment by cpate4** [comment]
... and here are two more PRs to be tracking re: getting this service off the ground:
- https://github.com/broadinstitute/terra-helmfile/pull/5314
- https://github.com/broadinstitute/terraform-ap-deployments/pull/1462/

**Comment by cpate4** [comment]
... and an update (based on the slack thread above) to the SourceClear stuff
https://github.com/broadinstitute/terraform-ap-deployments/pull/1466

**Review by cindy-broadinstitute — APPROVED** [review]

**Pull request merged**
